import { Inter, Montserrat } from "next/font/google";
import '../../public/css/style.css'
import Header from "./component/comman/Header";
import Footer from "./component/comman/Footer";

import Script from "next/script";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});


export const metadata = {
  title: "Latiyal GPS",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={`${inter.variable} ${montserrat.variable}`}>
        <Header />
        {children}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />
        <ToastContainer
          position="top-right"
          autoClose={2500}
          hideProgressBar={true}
          closeOnClick
          pauseOnHover
          draggable
          theme="dark"
          toastClassName="custom-toast"
          bodyClassName="custom-toast-body"
        />
        <Footer />
      </body>
    </html>
  );
}

