import { Inter, Montserrat } from "next/font/google";
import'../../public/css/style.css'
import Header from "./component/comman/Header";
import Footer from "./component/comman/Footer";
import"../app/component/Cart";
import Cart from "../app/component/Cart";


const inter = Inter({ subsets: ["latin"], weight: ["300","400","500","600","700"] });
const montserrat = Montserrat({ subsets: ["latin"], weight: ["300","400","500","600","700"] });

export const metadata = {
  title: "Latiyal GPS",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Montserrat:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-inter">
        <Header />
        <Cart />
        {children}
        <Footer />
      </body>
    </html>
  );
}

