import { Geist, Geist_Mono } from "next/font/google";
import'../../public/css/style.css'
import Header from "./component/comman/Header";
import Footer from "./component/comman/Footer";
import"../app/component/Cart";
import Cart from "../app/component/Cart";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Latiyal GPS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>
            <Cart/>
            {children}
        <Footer/>
      </body>
    </html>
  );
}
